#!/usr/bin/env python3.6
#cito M:755 O:0 G:0 T:/usr/local/bin/apt-newcache
#------------------------------------------------------------------------------
# Project Name      - PythonProjects/source/apt-newcache
# Started On        - Mon 19 Jun 22:18:00 BST 2023
# Last Change       - Mon 19 Jun 23:00:17 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Simply allow APT to completely rebuild the package cache by clearing out
# relevant files in the '/var/lib/apt/lists' directory, but easily and tidily.
#------------------------------------------------------------------------------

import os
import sys
import shutil

Path = '/var/lib/apt/lists'

if len(sys.argv) > 1:
	print(f"Err: No arguments accepted.", file = sys.stderr)
	exit(1)

try:
	for Base in os.listdir(Path):
		File = os.path.join(Path, Base)

		if os.path.isfile(File):
			if Base != 'lock':
				os.remove(File)
		elif os.path.isdir(File):
			shutil.rmtree(File)
except FileNotFoundError:
	print(f"Err: Directory '{Path}' not found.", file = sys.stderr)
	exit(1)
except PermissionError:
	print("Err: Permission denied -- are you 'root'?", file = sys.stderr)
	exit(1)
