#!/usr/bin/env python3.6

#------------------------------------------------------------------------------
# Project Name      - PythonProjects/source/lsbins
# Started On        - Sat 28 Nov 02:02:41 GMT 2020
# Last Change       - Mon 30 Nov 05:07:43 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# A Python 3.6 re-write of Perl-written LSBins, originally written in Shell.
#
# Extended Regular Expressions are always enabled in this Python re-write.
#
# Thanks go to 'aloussase' via #1 in 'PythonProjects' for helping me to figure
# some stuff out.
#
# Features:
#
#TODO: Enable ERE, per the Perl version of LSBins.
#
# Bugs:
#
#TODO: Name VS OldName in final loop, when describing, isn't working at all.
#
# Dependencies:
#
#   man-db (>= 2.8.3-2)
#   python3.6 (>= 3.6.9)
#------------------------------------------------------------------------------

from os import getenv, path, listdir, system, access, R_OK, X_OK, popen
from re import match, IGNORECASE, sub
from sys import argv, stderr

CurVer = '2020-11-28'
Progrm = 'lsbins'

def Usage():
	print(f'''Usage: {Progrm} [OPTS] [MATCH]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.
		  -N, --nodescribe         - Omit the short description.
		  -i, --ignore-case        - Search case-insensitively.\
	'''.replace('\t', ''))

def Err(Exit, String):
	print(f'ERROR: {String}', file=stderr)
	if Exit > 0: exit(Exit)

NoDescribe = False
CaseInsen = False

while len(argv) > 1:
	if match('^(--help|-h)$', argv[1]):
		Usage(); exit(0)
	elif match('^(--version|-v)$', argv[1]):
		print(CurVer); exit(0)
	elif match('^(--ignore-case|-i)$', argv[1]):
		CaseInsen = True
	elif match('^(--nodescribe|-N)$', argv[1]):
		NoDescribe = True
	elif match('^-', argv[1]):
		Err(1, 'Unrecognised option(s) specified.')
	else:
		break

	argv.pop(0)

if len(argv) > 2: Err(1, 'Only one MATCH is allowed.')

if len(argv) == 1 and CaseInsen is True:
	Err(1, "Option '--ignore-case|-i' provided, but missing MATCH.")

Executables = set()
for Dir in getenv('PATH').split(':'):
	if not path.isdir(Dir): next

	for File in listdir(Dir):
		if not path.isfile(File): next
		if not access(File, R_OK): next
		if not access(File, X_OK): next

		Executables.add(File)

Executables = sorted(Executables)

def DoMatch(FileName):
	if len(argv) == 1: return(1)

	if CaseInsen is True:
		if match(argv[1], FileName, IGNORECASE): return(1)
	else:
		if match(argv[1], FileName): return(1)

	return(0)

if NoDescribe is not True and 'man' in Executables:
	Data = popen(f'man -f {" ".join(Executables)} 2> /dev/null').read()

	OldName = ''
	for Line in Data.splitlines():
		Name = Line.split()[0]

		# Using `OldName` to avoid alternative descriptions.
		if Name.lower() is OldName.lower(): next

		# Can't get back-referencing to work how it usually would. So, unlike
		# the Perl version of LSBins, the first character won't be capitalized.
		Desc = sub('^.* - ', '', Line)

		DoMatch(Name) and print(f"{Name} - {Desc}")

		OldName = Name
else:
	for File in Executables:
		if DoMatch(File): next
		print(File)
