#!/usr/bin/env python3.6
#cito M:755 O:0 G:0 T:/usr/bin/mplay
#------------------------------------------------------------------------------
# Project Name      - PythonProjects/source/mplay
# Started On        - Fri 27 Nov 15:32:15 GMT 2020
# Last Change       - Sat 28 Nov 02:04:28 GMT 2020
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Rewrite of Shell-written `mplay` wrapper for MOC, in Python.
#
# Dependencies:
#
#   python3.6 (>= 3.6.9)
#------------------------------------------------------------------------------

from os import path, getenv, listdir, system
from sys import argv, stderr
from re import match

CurVer = '2020-11-27'
Progrm = 'mplay'

def Usage():
	print(f"""Usage: {Progrm} [OPTS] [DIR]

		  -h, --help               - Display this help information.
		  -v, --version            - Output the version datestamp.
		  -o, --run-once           - Exit the MOC server when closed.

		  Where DIR is the location in which music is to be found.
		""".replace('\t', ''))

def Err(Exit, String):
	stderr.write(f'ERROR: {String}\n')
	Exit > 0 and exit(Exit)

ThemeDir = '/usr/share/moc/themes'
ThemeFile = ThemeDir + '/tfl_moc_theme'
MusicDir = getenv('HOME') + '/Music'

while len(argv) > 1:
	if match('^(--help|-h)$', argv[1]):
		Usage(); exit(0)
	elif match('^(--version|-v)$', argv[1]):
		print(f"{CurVer}"); exit(0)
	elif match('^(--once|-o)$', argv[1]):
		DoOnce = 'True'
	elif match('^-', argv[1]):
		Err(0, 'Incorrect argument(s) specified.')
	else:
		break

	argv.pop(0)

if len(argv) == 2:
	if not path.isdir(argv[1]):
		Err(1, f"Music directory '{argv[1]}' not found.")
elif len(argv) > 2:
	Err(1, 'Too many arguments provided.')
else:
	MusicDir = argv[1]

if not path.isdir(ThemeDir):
	Err(1, f"Theme directory '{ThemeDir}' not found.")
elif not path.isfile(ThemeFile):
	Err(1, f"Theme file '{ThemeFile}' not found.")

Executables = []
for Dir in getenv('PATH').split(':'):
	if path.isdir(Dir):
		Files = listdir(Dir)
		Executables += Files

'mocp' in Executables or Err(1, "Dependency 'mocp' not met.")

system(
	f'''mocp -nT "{ThemeFile}"                \
	-O ShowFormat=yes                         \
	-O ShowTime=no                            \
	-O Shuffle=no                             \
	-O HideFileExtension=yes                  \
	-O SavePlaylist=no                        \
	-O TagsCacheSize=3000                     \
	-O PlaylistNumbering=yes                  \
	-O Layout1="playlist(50%,50%,50%,50%)"    \
	-O FollowPlayedFile=yes                   \
	-O ModPlug_NoiseReduction=yes             \
	-O ModPlug_ResamplingMode=FIR             \
	-O CanStartInPlaylist=yes                 \
	-O ResampleMethod=SincMediumQuality       \
	-O UseMimeMagic=no                        \
	-O ShowHiddenFiles=no                     \
	-O InputBuffer=512                        \
	-O OutputBuffer=512                       \
	-O Prebuffering=256                       \
	-m "{MusicDir}"'''
)
