#!/usr/bin/env python3.6

#------------------------------------------------------------------------------
# Project Name      - PythonProjects/source/puke
# Started On        - Tue  6 Jun 23:36:54 BST 2023
# Last Change       - Fri 28 Jul 00:05:39 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Violently disgust your co-workers with unnecessary rainbows.
#------------------------------------------------------------------------------

import os, sys, random

try:
	File = sys.argv[1]
except IndexError:
	print('Err: File path required.', file = sys.stderr)
	sys.exit(1)

Colors = []
for Color in list(range(31, 38)) + list(range(91, 98)):
	Colors.append("\033[" + str(Color) + 'm')

Styles = ("\033[0m", "\033[1m", "\033[2m", "\033[3m")

try:
	with open(File, 'rt', encoding = 'utf-8') as FH:
		Lines = map(str.rstrip, FH.readlines())
except FileNotFoundError:
	print(f"Err: File '{File}' not found.", file = sys.stderr)
	sys.exit(1)
except PermissionError:
	print(f"Err: File '{File}' inaccessible.", file = sys.stderr)
	sys.exit(1)

for Char in "\n".join(Lines):
	RandColorIndex = random.randint(0, len(Colors) - 1)
	RandStyleIndex = random.randint(0, len(Styles) - 1)
	RandColor = Colors[RandColorIndex]
	RandStyle = Colors[RandStyleIndex]

	print(f"{RandStyle}{RandColor}{Char}\033[0m", end = '')

print()
