#!/usr/bin/env python3.6

#------------------------------------------------------------------------------
# Project Name      - PythonProjects/source/total-ram
# Started On        - Wed  7 Jun 00:11:39 BST 2023
# Last Change       - Wed  2 Aug 23:36:59 BST 2023
# Author E-Mail     - terminalforlife@yahoo.com
# Author GitHub     - https://github.com/terminalforlife
#------------------------------------------------------------------------------
# Displays the total RAM found on the system, using the '/proc/meminfo' file.
# This starts at K, hence a null value for bytes being omitted from `Human()`.
#------------------------------------------------------------------------------

import sys

def Human(Ks: int, Power = 1024) -> str:
	for Unit in 'K', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y':
		if Ks < Power:
			Out = f"{Ks:0.1f}"
			if Out[-2:] == '.0':
				Out = Out[0:-2]

			return(f"{Out}{Unit}")

		Ks /= Power

File = '/proc/meminfo'

try:
	with open(File, 'rt') as FH:
		Lines = map(str.rstrip, FH.readlines())
except FileNotFoundError:
	print(f"Err: File '{File}' not found.", file = sys.stderr)
	sys.exit(1)
except PermissionError:
	print(f"Err: File '{File}' inaccessible.", file = sys.stderr)
	sys.exit(1)

Digits = ''
for Line in Lines:
	Key, Value = Line.rstrip().split(':')[0:2]

	if Key != 'MemTotal': continue

	for Char in Value:
		if Char.isdigit():
			Digits += Char

	break

print(Human(int(Digits)))
